// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMap: typeof import('./src/components/aMap/index.vue')['default']
    CalendarBox: typeof import('./src/components/CalendarBox/index.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber/index.vue')['default']
    OilPriceCalculator: typeof import('./src/components/OilPriceCalculator/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/components/test/index.vue')['default']
    Year: typeof import('./src/components/Year/index.vue')['default']
  }
}
