name: fundTask4
on:
  workflow_dispatch:
  schedule:
    #时间格式 minute hour day month week 设置的时间是UTC 不是北京时间
    - cron: "0 7 * * *"

jobs:
  start:
    # 运行环境为最新版的Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 

      #安装node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # 安装依赖并且执行脚本
      - name: npm install
        run: npm install
      
      - name: Start task
        run: node fundTask.js

      # 提交并推送修改
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "update fund data"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.FUND_TOKEN }}
          
      # 生成静态文件
      - name: Build
        run: npm install && npm run actionBuild

      # 部署到 GitHub Pages
      - name: Deploy
        # 使用别人写好的一个 action
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # 这里的 ACCESS_TOKEN 名字需要和下文中的相对应
          ACCESS_TOKEN: ${{ secrets.FUND_TOKEN }}
          # 打包后的文件部署到哪个分支上
          BRANCH: gh-pages
          # 打包后的文件在哪里
          FOLDER: dist
